CREATE TABLE `library`.`book` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TITLE` VARCHAR(50) NULL,
  `PUBLISH_YEAR` INT NULL,
  `AUTHOR` VARCHAR(255) NULL,
  PRIMARY KEY (`ID`));

CREATE TABLE `library`.`employee` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(255) NULL,
  `DATE_OF_BIRTH` DATE NULL,
  `EMAIL` VARCHAR(50) NULL,
  PRIMARY KEY (`ID`));

CREATE TABLE `library`.`employee_book` (
  `BOOK_ID` INT NULL,
  `EMPLOYEE_ID` INT NULL,
  `ID` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ID`));