INSERT INTO `library`.`book` (`TITLE`, `PUBLISH_YEAR`, `AUTHOR`) VALUES ('Yevgenii Onegin', '2008', 'Pushkin A.S.');
INSERT INTO `library`.`book` (`TITLE`, `PUBLISH_YEAR`, `AUTHOR`) VALUES ('Pikovaya Dama', '2012', 'Pushkin A.S.');
INSERT INTO `library`.`book` (`TITLE`, `PUBLISH_YEAR`, `AUTHOR`) VALUES ('Master i Margarita', '2016', 'Bulgakov M.A.');
INSERT INTO `library`.`book` (`TITLE`, `PUBLISH_YEAR`, `AUTHOR`) VALUES ('Voina i Mir', '2017', 'Tolstoi L.N.');
INSERT INTO `library`.`book` (`TITLE`, `PUBLISH_YEAR`, `AUTHOR`) VALUES ('Lyudi na bolote', '2013', 'Melej I.P.');
INSERT INTO `library`.`book` (`TITLE`, `PUBLISH_YEAR`, `AUTHOR`) VALUES ('Alpiiskaya balada', '2012', 'Bykov V.V.');
INSERT INTO `library`.`book` (`TITLE`, `PUBLISH_YEAR`, `AUTHOR`) VALUES ('Anna Karenina', '2015', 'Tolstoi L.N.');
INSERT INTO `library`.`book` (`TITLE`, `PUBLISH_YEAR`, `AUTHOR`) VALUES ('Skazki', '2016', 'Pushkin A.S.');
INSERT INTO `library`.`book` (`TITLE`, `PUBLISH_YEAR`, `AUTHOR`) VALUES ('Dubrovskii', '2017', 'Pushkin A.S.');
INSERT INTO `library`.`book` (`TITLE`, `PUBLISH_YEAR`, `AUTHOR`) VALUES ('Sobachee serdce', '2015', 'Bulgakov M.A.');
INSERT INTO `library`.`book` (`TITLE`, `PUBLISH_YEAR`, `AUTHOR`) VALUES ('Belaya gvardiya', '2012', 'Bulgakov M.A.');
INSERT INTO `library`.`book` (`TITLE`, `PUBLISH_YEAR`, `AUTHOR`) VALUES ('Rokovyie yaica', '2013', 'Bulgakov M.A.');
INSERT INTO `library`.`book` (`TITLE`, `PUBLISH_YEAR`, `AUTHOR`) VALUES ('Voskresenie', '2014', 'Tolstoi L.N.');
INSERT INTO `library`.`book` (`TITLE`, `PUBLISH_YEAR`, `AUTHOR`) VALUES ('Detstvo', '2015', 'Tolstoi L.N.');
INSERT INTO `library`.`book` (`TITLE`, `PUBLISH_YEAR`, `AUTHOR`) VALUES ('Unost', '2017', 'Tolstoi L.N.');
INSERT INTO `library`.`book` (`TITLE`, `PUBLISH_YEAR`, `AUTHOR`) VALUES ('Otrochestvo', '2016', 'Tolstoi L.N.');
INSERT INTO `library`.`book` (`TITLE`, `PUBLISH_YEAR`, `AUTHOR`) VALUES ('Podyh navalnicy', '2016', 'Melej I.P.');
INSERT INTO `library`.`book` (`TITLE`, `PUBLISH_YEAR`, `AUTHOR`) VALUES ('Mertvym ne bolno', '2014', 'Bykov V.V.');
INSERT INTO `library`.`book` (`TITLE`, `PUBLISH_YEAR`, `AUTHOR`) VALUES ('Obelisk', '2015', 'Bykov V.V.');
INSERT INTO `library`.`book` (`TITLE`, `PUBLISH_YEAR`, `AUTHOR`) VALUES ('Sotnikov', '2016', 'Bykov V.V.');
INSERT INTO `library`.`book` (`TITLE`, `PUBLISH_YEAR`, `AUTHOR`) VALUES ('Demon', '2017', 'Lermontov M.U.');
INSERT INTO `library`.`book` (`TITLE`, `PUBLISH_YEAR`, `AUTHOR`) VALUES ('Geroy nashego vremeni', '2016', 'Lermontov M.U.');
INSERT INTO `library`.`book` (`TITLE`, `PUBLISH_YEAR`, `AUTHOR`) VALUES ('Borodino', '2014', 'Lermontov M.U.');
INSERT INTO `library`.`book` (`TITLE`, `PUBLISH_YEAR`, `AUTHOR`) VALUES ('Maskarad', '2017', 'Lermontov M.U.');
INSERT INTO `library`.`book` (`TITLE`, `PUBLISH_YEAR`, `AUTHOR`) VALUES ('Vii', '2017', 'Gogol N.V.');
INSERT INTO `library`.`book` (`TITLE`, `PUBLISH_YEAR`, `AUTHOR`) VALUES ('Taras Bulba', '2012', 'Gogol N.V.');
INSERT INTO `library`.`book` (`TITLE`, `PUBLISH_YEAR`, `AUTHOR`) VALUES ('Mertvye dushi', '2014', 'Gogol N.V.');
INSERT INTO `library`.`book` (`TITLE`, `PUBLISH_YEAR`, `AUTHOR`) VALUES ('Revizor', '2015', 'Gogol N.V.');
INSERT INTO `library`.`book` (`TITLE`, `PUBLISH_YEAR`, `AUTHOR`) VALUES ('Vechera na hutore bliz Dikanki', '2016', 'Gogol N.V.');
INSERT INTO `library`.`book` (`TITLE`, `PUBLISH_YEAR`, `AUTHOR`) VALUES ('Nos', '2017', 'Gogol N.V.');
INSERT INTO `library`.`book` (`TITLE`, `PUBLISH_YEAR`, `AUTHOR`) VALUES ('Idiot', '2012', 'Dostoevskii F.M.');
INSERT INTO `library`.`book` (`TITLE`, `PUBLISH_YEAR`, `AUTHOR`) VALUES ('Bratia Karamazovy', '2013', 'Dostoevskii F.M.');
INSERT INTO `library`.`book` (`TITLE`, `PUBLISH_YEAR`, `AUTHOR`) VALUES ('Prestuplenie i nakazanie', '2014', 'Dostoevskii F.M.');
INSERT INTO `library`.`book` (`TITLE`, `PUBLISH_YEAR`, `AUTHOR`) VALUES ('Besy', '2015', 'Dostoevskii F.M.');
INSERT INTO `library`.`book` (`TITLE`, `PUBLISH_YEAR`, `AUTHOR`) VALUES ('Igrok', '2016', 'Dostoevskii F.M.');
INSERT INTO `library`.`book` (`TITLE`, `PUBLISH_YEAR`, `AUTHOR`) VALUES ('Belye nochi', '2017', 'Dostoevskii F.M.');
INSERT INTO `library`.`book` (`TITLE`, `PUBLISH_YEAR`, `AUTHOR`) VALUES ('Lolita', '2014', 'Nabokov V.V.');
INSERT INTO `library`.`book` (`TITLE`, `PUBLISH_YEAR`, `AUTHOR`) VALUES ('Zashita Lujina', '2016', 'Nabokov V.V.');
INSERT INTO `library`.`book` (`TITLE`, `PUBLISH_YEAR`, `AUTHOR`) VALUES ('Korol, dama, valet', '2017', 'Nabokov V.V.');
INSERT INTO `library`.`book` (`TITLE`, `PUBLISH_YEAR`, `AUTHOR`) VALUES ('12 stulev', '2015', 'Ilf I. Petrov E.');
INSERT INTO `library`.`book` (`TITLE`, `PUBLISH_YEAR`, `AUTHOR`) VALUES ('Zolotoi telenok', '2016', 'Ilf I. Petrov E.');
INSERT INTO `library`.`book` (`TITLE`, `PUBLISH_YEAR`, `AUTHOR`) VALUES ('Bespridannica', '2017', 'Ostovskii A.N.');
INSERT INTO `library`.`book` (`TITLE`, `PUBLISH_YEAR`, `AUTHOR`) VALUES ('Groza', '2012', 'Ostovskii A.N.');
INSERT INTO `library`.`book` (`TITLE`, `PUBLISH_YEAR`, `AUTHOR`) VALUES ('Vishnevyi sad', '2013', 'Chehov A.P.');
INSERT INTO `library`.`book` (`TITLE`, `PUBLISH_YEAR`, `AUTHOR`) VALUES ('Chaika', '2014', 'Chehov A.P.');
INSERT INTO `library`.`book` (`TITLE`, `PUBLISH_YEAR`, `AUTHOR`) VALUES ('Dama s sobachkoi', '2015', 'Chehov A.P.');
INSERT INTO `library`.`book` (`TITLE`, `PUBLISH_YEAR`, `AUTHOR`) VALUES ('3 sestry', '2016', 'Chehov A.P.');
INSERT INTO `library`.`book` (`TITLE`, `PUBLISH_YEAR`, `AUTHOR`) VALUES ('Otcy I deti', '2015', 'Turgenev I.S.');
INSERT INTO `library`.`book` (`TITLE`, `PUBLISH_YEAR`, `AUTHOR`) VALUES ('Mumu', '2012', 'Turgenev I.S.');
INSERT INTO `library`.`book` (`TITLE`, `PUBLISH_YEAR`, `AUTHOR`) VALUES ('Dvoryanskoe gnezdo', '2014', 'Turgenev I.S.');



INSERT INTO `library`.`employee` (`NAME`, `DATE_OF_BIRTH`, `EMAIL`) VALUES ('Ivan Ivanov', '1997-01-01', 'ivanov@mai.ru');
INSERT INTO `library`.`employee` (`NAME`, `DATE_OF_BIRTH`, `EMAIL`) VALUES ('Petr Petrov', '1996-02-02', 'petrov@mail.ru');
INSERT INTO `library`.`employee` (`NAME`, `DATE_OF_BIRTH`, `EMAIL`) VALUES ('Roma Romanov', '1995-03-03', 'romanov@mail.ru');
INSERT INTO `library`.`employee` (`NAME`, `DATE_OF_BIRTH`, `EMAIL`) VALUES ('Lena Lenova', '1998-04-04', 'lenova@mail.ru');
INSERT INTO `library`.`employee` (`NAME`, `DATE_OF_BIRTH`, `EMAIL`) VALUES ('Stepan Stepanov', '1996-05-05', 'stepanov@mail.ru');
INSERT INTO `library`.`employee` (`NAME`, `DATE_OF_BIRTH`, `EMAIL`) VALUES ('Boris Borisov', '1995-06-06', 'borisov@mail.ru');
INSERT INTO `library`.`employee` (`NAME`, `DATE_OF_BIRTH`, `EMAIL`) VALUES ('Pavel Pavlov', '1997-07-07', 'pavlov@mail.ru');
INSERT INTO `library`.`employee` (`NAME`, `DATE_OF_BIRTH`, `EMAIL`) VALUES ('Anna Annova', '1998-08-08', 'annova@mail.ru');
INSERT INTO `library`.`employee` (`NAME`, `DATE_OF_BIRTH`, `EMAIL`) VALUES ('Katia Katina', '1999-09-09', 'katina@mail.ru');
INSERT INTO `library`.`employee` (`NAME`, `DATE_OF_BIRTH`, `EMAIL`) VALUES ('Oleg Olegov', '1996-10-10', 'olegov@mail.ru');
INSERT INTO `library`.`employee` (`NAME`, `DATE_OF_BIRTH`, `EMAIL`) VALUES ('Vasia Vasilev', '1997-11-11', 'vasilev@mail.ru');
INSERT INTO `library`.`employee` (`NAME`, `DATE_OF_BIRTH`, `EMAIL`) VALUES ('Vova Vovin', '1998-12-12', 'vovin@mail.ru');

